### ISSUE TITLE
Error Napspace global:: already contains a definition for 'Value Container'

### ISSUE THREAD

**Issue by EmilyRobotics** [Pjaerr/1935#2]
Hello,

I opened the game in unity and there was an error : Assets/Scripts/ValueObjects.cs(5,14): error CS0101: The namespace `global::' already contains a definition for `ValueContainer'

I tried changing valueobjects class to ValueObjects, but then i got a lot of other errors

Any idea on how to fix?

Thank you

**Comment by Pjaerr** [comment]
My last commit broke a bunch of things as I am just getting back into working on the project and I am experimenting with changing how values are stored. There isn't much of a game there yet anyway, just a bunch of mechanics tied together. You could grab an earlier commit.
